// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYsahSmJpDgK7MQs-2PjWznhzBbM9KMeA',
    appId: '1:935358101985:android:201c10e06fd95fdc907aa0',
    messagingSenderId: '935358101985',
    projectId: 'speakean-961d1',
    databaseURL: 'https://speakean-961d1-default-rtdb.firebaseio.com',
    storageBucket: 'speakean-961d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnmC56ab1NhHkfsOLrGoNRM9VJkVQ_GVA',
    appId: '1:935358101985:ios:cca9323ea03892e6907aa0',
    messagingSenderId: '935358101985',
    projectId: 'speakean-961d1',
    databaseURL: 'https://speakean-961d1-default-rtdb.firebaseio.com',
    storageBucket: 'speakean-961d1.appspot.com',
    iosClientId: '935358101985-8o3ua9df0q6fdgr8pmun34l0prte1iu7.apps.googleusercontent.com',
    iosBundleId: 'com.speakean.speakean',
  );
}
